### ISSUE TITLE
Sample Image File

### ISSUE THREAD

**Issue by gabynordic** [haraldg/thermocam-tools#1]
I am looking to test this code before I invest in a camera. Would you happen to have any sample radiometric jpeg files so that I could test this? 

Thanks!

**Comment by haraldg** [comment]
I guess adding some example files is a good idea. Are there any specific
points of interest for you?

However the programs don't use radiometric jpeg: Only DIY-Thermocam .DAT
files (containing sensor values) and their own trivial file format
(temperature values as 32bit floats). The graphical representation
can only be saved to conventional image files at the moment.

**Comment by supertobi** [comment]
Just put something online. The content is not that impotent. Your hand or a house will work. (Or a cat, the internet loves cat content. ;))

**Comment by haraldg** [comment]
Thanks for the reminder. I'm somewhat busy with real life and completely forgot about this issue minutes after answering ... :(

Anyway a just committed a few images that allow to test the calibration procedure.
